version: "3.7"
services:
  puppet:
    build: .
    image: puppetserver:latest
    hostname: puppet.example.com
    restart: unless-stopped
    devices:
      - "/dev/urandom:/dev/urandom"
    ports:
      - "8140:8140"
    networks:
      puppetnet:
        aliases:
          - puppet.example.com
    healthcheck:
      test: /healthcheck.sh
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 5m
    volumes:
      - puppetserver-code:/etc/puppetlabs/code
      - puppetserver-ssl:/etc/puppetlabs/puppet/ssl
      - pupeptserver-ssh:/etc/puppetlabs/ssh
      # - puppetserver-ca:/etc/puppetlabs/git/ca
      # - pupeptserver-r10k-cache:/opt/puppetlabs/server/data/puppetserver/r10k
      # - puppetserver-r10k-conf: /etc/puppetlabs/r10k/r10k.yaml
      # - puppetserver-auth-conf: /etc/puppetlabs/puppetserver/conf.d/auth.conf
      # - puppetserver-metrics-conf: /etc/puppetlabs/puppetserver/conf.d/metrics.conf
      # - puppetserver-puppetserver-conf: /etc/puppetlabs/puppetserver/conf.d/puppetserver.conf
      # - puppetserver-reports: /opt/puppetlabs/server/data/puppetserver/reports
    environment:
      CERTNAME: "puppet.example.com"
      DNS_ALT_NAMES: "puppet,puppet.example.com"
      PUPPETDB_SERVER_URLS: "https://puppetdb:8081"
      # SSH_HOST_KEY_CHECK: "true"
      # SHOW_SSH_KEY: "true"
      # TRUST_SSH_FIRST_CONNECT: "true"
      # R10K_ON_STARTUP: "false"
      # R10K_SOURCE1: "production,ssh://git@gitlab.example.com:2222/dan/prod-control-repo.git,false"
      # R10K_SOURCE2: "puppet,ssh://git@gitlab.example.com:2222/dan/control-puppet.git"
      # AUTOSIGN: "true"


  # puppetserver-agent:
  #   image: puppetserver
  #   restart: unless-stopped
  #   depends_on:
  #     - puppetserver
  #   network_mode: service:puppetserver
  #   volumes:
  #     - pupeptserver-code:/etc/puppetlabs/code
  #   command: puppet agent -v --no-daemonize --logdest console -w 30s

networks:
  puppetnet:
    external: true

volumes:
  puppetserver-code:
  puppetserver-ssl:
  pupeptserver-ssh:
